### ISSUE TITLE
Fix broken graphs/tech-stack-by-role API endpoint; update tech stack visualization 

### ISSUE THREAD

**Issue by opeterschmidt** [BloomTech-Labs/underdog-devs-ds-a#137]
Graph function was written based on an outdated schema version; needs to be updated to work again

Graph as outlined in [tech-stack-visualization.ipynb](https://github.com/BloomTech-Labs/underdog-devs-ds-a/blob/main/notebooks/tech-stack-visualization.ipynb) is not the most appropriate visualization for this info:

- Total number of members (mentees and mentors combined) in each stack is not necessarily the most salient information, rather how many mentors and mentees (separately) are in each tech stack
- A separate graph each for mentor stacks and mentee stacks would be easier to parse and compare at a glance

**Comment by jinjahninjah** [comment]
Created BL-390 out of this issue.
