### ISSUE TITLE
Documentation Updates

### ISSUE THREAD

**Issue by opeterschmidt** [BloomTech-Labs/underdog-devs-ds-a#139]
Various documentation updates, including: 

**app repo**
readme updates: computer_assignment.py and schema.py are not currently accounted for

**data_generators repo**
needs a readme

**In-file documentation needs** (typos, gaps, and outdated references)
app.py
model.py
graphs.py
utilities.py
schema.py

**Comment by jinjahninjah** [comment]
Created BL-392 out of this issue.
