### ISSUE TITLE
DS - api.py endpoint for /{collections}/search cannot access Meetings or Feedback collections

### ISSUE THREAD

**Issue by sayerjk** [BloomTech-Labs/underdog-devs-ds-a#141]
This endpoint is functional when searching Mentor and Mentee collections, but returns a 500 error when you attempt any search in the Meetings or Feedback collections. Was this feature abandoned? I think it is worth restoring functionality for searching all current and future collections.

**Comment by jinjahninjah** [comment]
Created BL-394 out of this issue.
