### ISSUE TITLE
Implement response NLP topic modelling/LDA

### ISSUE THREAD

**Issue by ErinNC** [BloomTech-Labs/underdog-devs-ds-a#152]
Continuation of work from BL-134. Rather than collecting counts of single words, our goal is to analyze the user response text for phrases and topics. The collection we will work on is currently called "Responses": what the users are looking for in the community. There will be a linked issue for the notebook related to this issue.

**Comment by jinjahninjah** [comment]
Go ahead and work on the notebook first and once that's locked down, we do the implementation 👍
