### ISSUE TITLE
Update Meeting schema 

### ISSUE THREAD

**Issue by ErinNC** [BloomTech-Labs/underdog-devs-ds-a#176]
Check with FE if they have a form made for meetings and either match that or the schema specified in attached spreadsheet.

<img width="1022" alt="Screen Shot 2022-07-18 at 11 40 25 AM" src="https://user-images.githubusercontent.com/96785813/179549126-b5f79d7e-8aa4-48ae-99c0-b88e9427811b.png">

**Comment by jinjahninjah** [comment]
BL-586 created
