### ISSUE TITLE
API Error Handling

### ISSUE THREAD

**Issue by BrokenShell** [BloomTech-Labs/underdog-devs-ds-a#181]
Add error handling for endpoints that can throw unexpected exceptions.
- MongoDB: Some fields are specified as unique, but the API only throws a generic 500 with no helpful info.

Possible fix for `create/mentor` endpoint...
```python
try:
    return {"result": API.db.create("Mentors", data.dict())}
except DuplicateKeyError:
    return {"result": f"The field 'profile_id' must be unique, '{data.profile_id}' already exists."}
```

**Comment by jinjahninjah** [comment]
BL-578 created.
