### ISSUE TITLE
Random Datetime Quest

### ISSUE THREAD

**Issue by BrokenShell** [BloomTech-Labs/underdog-devs-ds-a#186]
### Quest Objective
Design a function (or class) that produces a random datetime object within an input range. This function could be very useful for generating mock data that is suitable for time series analysis. This will be an indispensable tool for generating mock datasets that can be used for designing the required charts and graphs for this project.

### Recommended Signature
```random_datetime(start: datetime, stop: datetime) -> datetime```

### Story Point Value Range
MVP: 2 points
Pythonic: 5 points

#### Point Award Criteria
MVP: It works, but the code lacks some quality or nuance that is holding it back from greatness.
Pythonic: Jedi Master Python Poetry.

**Comment by woodbenwood** [comment]
this issue became this ticket: https://github.com/BloomTech-Labs/underdog-devs-ds-a/pull/194
