### ISSUE TITLE
Database Restructure Documentation (Jira Ticket Request)

### ISSUE THREAD

**Issue by zdravoj** [BloomTech-Labs/underdog-devs-ds-a#196]
A project was initiated to restructure the databases to be independent, clean, and comprehensible. This project needs documentation including a description of the problem, steps taken to solve it, its current state, and future needs, as well as any supporting files.

This documentation has already been completed and the pull request can be found in the [Underdog documentation on GitHub](https://github.com/BloomTech-Labs/underdog-devs-docs).

The purpose of this GitHub issue is to create a Jira ticket to be attached to this pull request so points can be awarded for the work.

**Comment by jinjahninjah** [comment]
BL-712 created 7.29.22
