### ISSUE TITLE
API endpoint error /create/feedback

### ISSUE THREAD

**Issue by nikolayglushetskiy** [BloomTech-Labs/underdog-devs-ds-a#254]
When I try to create a duplicate feedback record  (for integration tests purpose) via POST /create/feedback endpoint, I got 500 Internal server error.

**Comment by BrokenShell** [comment]
Good catch! Can you look into this deeper and suggest a fix?

**Comment by nikolayglushetskiy** [comment]
I can fix by adding `try: except DuplicatKeyError` construction to mentee_router.py API file

**Comment by BrokenShell** [comment]
nope, that will just hide the problem. The bug is subtle, but it is fixable
