### ISSUE TITLE
DELETE Feedback API endpoint Error

### ISSUE THREAD

**Issue by nikolayglushetskiy** [BloomTech-Labs/underdog-devs-ds-a#256]
When I try to Delete e feedback entree using API DELETE Feedback endpoint, I always get 200 status, doesn't matter if we API had successfully deleted entree or there is no such entree. 

Also there is no uniformity in URLs names for UPDATE and DELETE. In Mentors there is `/update/mentor/{mentor_id}` url, same for mentees. In feedback url is `/update/feedback?ticked_id={ticked_id}`, same problem for DELETE URL

**Comment by randynobx** [comment]
The issue of always getting a 200 status (and `{"result":True}` is one that was recently brought up to me regarding all the endpoints by a web learner recently.

As a design decision, we should clarify what the 'intent' of a delete statement is:
1. To delete a specific datum in the db. If it doesn't exist, this is a failure.
2. To ensure that a certain datum does not exist in the db. As long as that datum is not present after the delete operation it is a success, regardless of its prior existence or non-existence.


The uniformity of update/delete URLs should definitely be addressed. That should be an easy fix.

**Comment by BrokenShell** [comment]
These are two separate issues... let's create tickets that represent individual problems with possible solutions.

**Comment by nikolayglushetskiy** [comment]
Who should create these tickets?

**Comment by BrokenShell** [comment]
In my view, deleting a record that doesn't exist isn't an error. Convince me I'm wrong.

**Comment by nikolayglushetskiy** [comment]
It is not an error, but the problem is that we have same output when we successfully delete an entry and if we not (for example if we put wrong query). In my opinion function should return some thing different , no matter oh what case

**Comment by nikolayglushetskiy** [comment]
We decide to leave it as it is.
