### ISSUE TITLE
DS: Some pep8 style improvements

### ISSUE THREAD

**Issue by gpwolfe** [BloomTech-Labs/underdog-devs-ds-a#270]
There are a few style improvements that could be quickly made: Some non-string lines (i.e., lines that ARE easily breakable) that extend past 79 characters and at least one star import that could be reduced to specific imports.

Below appears in seeds.py:
![Screen Shot 2022-11-17 at 17 24 43](https://user-images.githubusercontent.com/29279762/202501542-06b3a518-a0ac-4075-b494-c283808b9606.png)

Recommended story points: 1

**Comment by BrokenShell** [comment]
approved
