### ISSUE TITLE
DS Bug – Feedback update error when 'text' not included

### ISSUE THREAD

**Issue by gpwolfe** [BloomTech-Labs/underdog-devs-ds-a#272]
If we're going to continue using Feedback features, the update endpoint would be more usable if it did not require `text` to be included in the update dict. I believe a simple fix would suffice, as below, the added `if 'text' in data_dict:`
This should fix the error noted in the proper_integration_tests notebook in ~21st code cell

```@Router.patch("/update/feedback")
async def update_feedback(ticket_id: str, update_data: FeedbackUpdate):
    """Updates feedback
    <pre><code>
    @param ticket_id: str
    @param update_data: FeedbackUpdate
    @return JSON[Boolean] - indicates success or failure of update</pre></code>"""
    data_dict = update_data.dict(exclude_none=True)
    if 'text' in data_dict:
        data_dict = apply_sentiment(data_dict)
    return {"result": Router.db.update("Feedback", {"ticket_id": ticket_id}, data_dict)}
```

Suggested story points: 1

**Comment by BrokenShell** [comment]
Interesting, please come to office hours to discuss this!
